version: "1.0"

instances:
  cvat:
    build:
      context: .
      recipe: Singularity
    ports:
      - "8443:8443"
      - "8080:8080"
    build:
      context: .
      options:
        - fakeroot
    volumes:
      - ./cvat:/home/django/cvat
      - volumes/data:/home/django/data
      - volumes/keys:/home/django/keys
      - volumes/logs:/home/django/logs
      - volumes/models:/home/django/models
      - ./cvat-env.sh:/.singularity.d/env/92-common.sh

  cvatui:
    build:
      context: .
      recipe: Singularity.ui
      options:
        - fakeroot
    depends_on:
      - cvat
    ports:
      - "7080:7080"
    volumes:
      - ./cvat-env.sh:/.singularity.d/env/92-common.sh
